name: Validator

on:
  push:
    branches-ignore:
      - master

jobs:
  validator:
    name: Submission validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: User demo examples removed
        run: ./validator.sh 'remove_user_examples'
      - name: Testbench examples removed
        run: ./validator.sh 'remove_test_examples'
      - name: Notebook example removed
        run: ./validator.sh 'remove_notebook_example'
      - name: Testbench tests imported
        run: ./validator.sh 'test_import'
      - name: Referent implementation defined
        run: ./validator.sh 'test_ref_impl'
      - name: Testbench call for referent implementation
        run: ./validator.sh 'test_run'
      - name: Dependency check for user imports
        run: ./validator.sh 'module_import_user'
      - name: Dependency check for Testbench imports
        run: ./validator.sh 'module_import_test'
      - name: Prepare system for execution
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Testbench module to system
        run: pip install .
      - name: Pass tests for referent implementation
        run: ./validator.sh 'user_demo'
